CREATE TABLE "assessments" (
	"id" serial PRIMARY KEY NOT NULL,
	"record_email" boolean DEFAULT false NOT NULL,
	"email" text DEFAULT '' NOT NULL,
	"full_name" text NOT NULL,
	"company" text NOT NULL,
	"job_title" text NOT NULL,
	"industry" jsonb NOT NULL,
	"country" text NOT NULL,
	"company_size" jsonb NOT NULL,
	"time_consuming_tasks" jsonb NOT NULL,
	"task_to_automate" text NOT NULL,
	"current_tools" jsonb NOT NULL,
	"ai_familiarity" jsonb NOT NULL,
	"primary_goals" jsonb NOT NULL,
	"excited_features" jsonb NOT NULL,
	"monthly_budget" jsonb NOT NULL,
	"required_integrations" jsonb NOT NULL,
	"implementation_timeline" text NOT NULL,
	"feedback_willingness" text NOT NULL,
	"anything_else" text DEFAULT '' NOT NULL,
	"submitted_at" timestamp with time zone DEFAULT now() NOT NULL,
	"status" text DEFAULT 'new' NOT NULL
);
